<a href="https://colab.research.google.com/github/asifd1253/AI-ML/blob/main/lab2_28_08_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
print(np.__version__)


1.26.4


In [5]:
A1=np.array([1,2,3,4])
print(A1)

[1 2 3 4]


In [6]:
type(A1)

numpy.ndarray

In [7]:
A1.shape

(4,)

In [10]:
A1.size

4

In [11]:
A2=np.array([[1,2,3],[4,5,6]])
print(A2)

[[1 2 3]
 [4 5 6]]


In [12]:
type(A2)

numpy.ndarray

In [13]:
A2.shape

(2, 3)

In [14]:
A2.size

6

In [15]:
A2.ndim

2

In [20]:
A3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [21]:
A3.ndim

3

In [22]:
A3.size

9

In [23]:
A3.shape

(1, 3, 3)

In [24]:
z1=np.zeros(3)
print(z1)

[0. 0. 0.]


In [25]:
z1.shape

(3,)

In [26]:
z1.size

3

In [27]:
z1.ndim

1

In [28]:
type(z1)

numpy.ndarray

In [30]:
z2=np.zeros((3,4))
print(z2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
z2=np.zeros((3,4),dtype=int)
z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [32]:
type(z2)

numpy.ndarray

In [33]:
z2.shape

(3, 4)

In [34]:
z2.size

12

In [35]:
z2.ndim

2

In [37]:
z3=np.zeros((2,3,4))
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [38]:
z3.size

24

In [39]:
z3.shape

(2, 3, 4)

In [40]:
z3.ndim

3

In [41]:
type(z3)

numpy.ndarray

In [43]:
z3=np.zeros((2,3,4),dtype=int)
z3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [44]:
a1=np.ones(3)
a1

array([1., 1., 1.])

In [45]:
a1=np.ones(3,dtype=int)
a1

array([1, 1, 1])

In [47]:
a1.size

3

In [46]:
a1.shape


(3,)

In [48]:
a1.ndim

1

In [49]:
a2=np.ones((3,4))
a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
a2.size

12

In [51]:
a2.shape

(3, 4)

In [52]:
a2.ndim

2

In [53]:
a2=np.ones((3,4),dtype=int)
a2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [56]:
a3=np.ones((2,3,4))
a3

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [57]:
a3=np.ones((2,3,4),dtype=int)
a3

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [58]:
a3.size

24

In [59]:
a3.shape

(2, 3, 4)

In [61]:
f1=np.full(3,9)
f1

array([9, 9, 9])

In [62]:
f1=np.full(3,9,dtype=float)
f1

array([9., 9., 9.])

In [63]:
f2=np.full((2,3),9)
f2

array([[9, 9, 9],
       [9, 9, 9]])

In [64]:
f3=np.full((2,3,4),9)
f3

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])